### PR TITLE
Settings: About

### PR DESCRIPTION
**Pull request by vleong2332**
Display App Version and Data Path in Settings.

Also fix run error for Linux.

Resolves issue #353 

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-desktop/375)

### CODE REVIEW

**Comment by neutrinog** [comment]
@vleong2332 the settings page is now blank. If I delete the old data dir and try again everything loads up, but users' won't know how to do that.

**Comment by vleong2332** [comment]
@neutrinog what directory did you delete?

**Comment by neutrinog** [comment]
`~/AppData/translationstudio`

**Comment by neutrinog** [comment]
@vleong2332 any progress on this?

**Comment by vleong2332** [comment]
Yes. I fixed it. Look at commit 55a6118

**Pull request merged**
