### PR TITLE
Updated license pages

### PR DESCRIPTION
**Pull request by jag3773**
This PR fixes the verbiage regarding licensing.

### CODE REVIEW

**Comment by jag3773** [comment]
@neutrinog The same changes need to be made in the Android version where applicable.

**Comment by ChrisJarka** [comment]
Have you considered having the license page be source language specific?

**Comment by jag3773** [comment]
@ChrisJarka Currently using tS requires that you agree to release your contributions as BY-SA, so I've updated the text to reflect this more accurately.

I do think that a more generic framework would be helpful but that will have to come in another release that has the whole flow planned out, including the necessary UI components.

**Comment by ChrisJarka** [comment]
@jag3773 Excellent! It's good to see 'great minds thinking alike' only yours can implement mine can just ponder.

**Pull request merged**
