### PR TITLE
Bug fixes

### LINKED ISSUE #1280: Upgrade from 11.1 to 12.1 failed with error
Upgrade from 11.1 to 12.1 failed with error as in the snapshot:
image

### PR DESCRIPTION
**Pull request by neutrinog**
* the application can now be closed on macOS. #1278 
* the application can now be upgraded from 11.1 without any errors during the install. #1280
* Fixes tA not jumping to the article. #1283
* Fixes error dialog being hidden, and improves error messages. #1285
* Updates content #1286
* Preserves scroll position when resizing the tA window #1287

### CODE REVIEW

**Comment by neutrinog** [comment]
There are some builds that can be tested at https://github.com/unfoldingWord-dev/ts-desktop/releases/tag/untagged-10c13b04372bb62773d2

**Comment by elsylambert** [comment]
Tried to upgrade from 11.1 to 12.1.1((Hotfix) build), system is hung after I clicked on the .exe file.
image

**Comment by neutrinog** [comment]
@elsylambert I'm not able to reproduce that. Is it consistently freezing every time?

**Comment by elsylambert** [comment]
@neutrinog Yes, consistently every time.
These are the steps I followed:
1. Did a clean install of 11.1.
2. Imported a project and made edits.
3. Downloaded 12,1,1 hotfix build.
4. Clicked on the .exe file to install.
My cursor kept spinning forever till I ended the Task, I ended up rebooting my computer.
I tried this three times.

**Comment by elsylambert** [comment]
I tried once again this morning and v12.1.1 build 146 got installed successfully. Upgraded from v 11.1 to v 12.1.1.

**Comment by elsylambert** [comment]
@neutrinog - Upgrade from 11.1 to 12.1.1 is working fine in windows 64-bit machine.
- Clean Install of 12.1.1 is working fine.

**Comment by neutrinog** [comment]
@elsylambert I have some new builds for you to try out https://github.com/unfoldingWord-dev/ts-desktop/releases/tag/untagged-d99fe0490159afc118fb

These should fixes all the outstanding bugs.

**Comment by elsylambert** [comment]
Verified in v12.1.1 build 147.
- Clean Installtion and upgrade from 11.1 works fine.
- kn tA download works fine.
- kn tA article jumps to the selected Article.

**Comment by neutrinog** [comment]
@elsylambert check out the new builds here https://github.com/unfoldingWord-dev/ts-desktop/releases/tag/untagged-d7fbb4a5921a6501e60d

**Comment by elsylambert** [comment]
Verified in v12.1.1 build 148.
All the mentioned issues are fixed.
- unable to install on Windows #1282
- unable to close the app on macOS #1282
- errors while upgrading from 11.1 #1280
- tA is not jumping to the selected article. #1283
- unable to download kn tA.
- update packaged content #1286
- preserve scroll position when resizing tA window

**Pull request merged**
