### PR TITLE
Printing in UI

### PR DESCRIPTION
**Pull request by cdwhitfield73**
This completes issue #218, setting up printing from the UI side.  It also fixes an issue with words projects crashing on opening.  I also had to fix some of the back end printing code as the App.printer commands were not functional from the UI.

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-desktop/289)

### CODE REVIEW

**Comment by cdwhitfield73** [comment]
Added quick fixes for issues #274, #275, and #276

**Comment by RRohrssen** [comment]
@cdwhitfield73 What does this issue have to do with #274, #275, and #276?

**Comment by cdwhitfield73** [comment]
@RRohrssen : Nothing.  Just completing multiple issues on one pull request, since Joel had not merged it yet and I made more changes to the same branch.  Printing was just the "main" thing that this Pull Request has in it, which is why I used that for the title, but there are several commits that deal with other things as well.

**Comment by cdwhitfield73** [comment]
Added more code to this PR that completes issues #242 and #247.  Also re-hid settings button in menus because they are still not functional.

**Comment by cdwhitfield73** [comment]
Added fixes to publish page to complete issue #292

**Pull request merged**
