### PR TITLE
Auto-Backup

### LINKED ISSUE #303: Make backup automatic
- [x] Automatically run backups in the background when the user is working on projects.
- [x] Backup is in `.tstudio` format
- [x] User should be able to change where the backup is saved to (#205)
- [ ] User should be notified when backup is ongoing and when it is done

### PR DESCRIPTION
**Pull request by vleong2332**
Resolves #303 

Basic auto backup is run every 20 seconds when the user is "inside" a project. "-backup" is appended to the file name before the extension.

When the user changes the backup location from the settings, the backup files should be migrated. (NOTE: This needs to be re-verify when file dialog is fixed for electron, it was working with node-webkit).

[Review on Reviewable](https://reviewable.io/reviews/unfoldingword-dev/ts-desktop/368)

### CODE REVIEW

**Comment by RRohrssen** [comment]
@vleong2332 Does this mean that there is only 1 (one) backup file ever, and that it is overwritten 20 seconds later when the next auto backup occurs?

**Comment by tjklemz** [comment]
@RRohrssen yes. I believe this is how it is in Android. Vicky and I talked about the possibility of having a current, hourly, daily, weekly, and monthly, but we weren't sure if this was a priority atm.

**Comment by RRohrssen** [comment]
@vleong2332 @tjklemz where would this functionality prove to be useful? Do you intend for this to be augmented with GOGS so that a full history of changes is maintained? As it is, it seems very easy to envision the scenario where an inadvertent change becomes the only available version upon a crash.

Do you have anything that lays out the use case here, and possible recoveries from a user's perspective?

**Comment by neutrinog** [comment]
@vleong2332 the way android is doing it is running the auto backup on everything no matter where you are in the program. It grabs the commit hash of HEAD and uses that to keep track if a backup needs to be made. For example in android your backup folder looks like this:

```
uw-gen-aa/<comitt hash>.tstudio (just a single file in each dir)
...
uw-mat-aa/<comitt hash>.tstudio
uw-mrk-aa/<comitt hash>.tstudio
...
```

Then when the backup service runs it will compare the commit hash with the latest one. If they differ the old backup is removed and the new backup is made.

This is not the prettiest, but it does work. The key points are: 
* don't backup unless there was a change (for performance... maybe not a big deal with desktop so long as the ui is not frozen)
* run the backup against everything no matter where you are in the app

**Comment by neutrinog** [comment]
@vleong2332 can you change the backup file name to be `*.backup.tstudio` instead of using a dash?

**Comment by vleong2332** [comment]
@neutrinog so auto backup will backup *all* the current projects the user have?

**Comment by neutrinog** [comment]
@vleong2332 yes

**Comment by vleong2332** [comment]
@neutrinog @tjklemz will the manual backup (for individual project) follow the same naming convention? For example, `uw-obs-aa/<commit hash>.backup.tstudio`

**Comment by neutrinog** [comment]
@vleong2332 no. They will be exported as `uw-obs-aa.tstudio`.

Also maybe we should place automatic backups in their own folder. Perhaps `~/translationStudio/backups/automatic`?

**Comment by vleong2332** [comment]
@neutrinog so it sounds like we're trying to address 2 different kinds of backup here. It's not simply calling the manual backup automatically, which is what this PR for:

1. **manual individual backup**:
   - This is done when a user choose to perform a backup inside a project
   - The naming will be `<project_name>.tstudio`
   - The location is up to the user, since the user have the ability to navigate to his desired folder

2. **automatic backup**:
   - This is done automatically when there's changes to any project
   - The naming will be `<commit_hash>.backup.tstudio`
   - The location is set to `~/translationStudio/backups/automatic/<project_folder>/`

My questions are:
- For no. 1, what should be the default location? Will it be `~/translationStudio/backups/`?
- For no. 2, are we allowing the user to change the location?
- For "backup location" setting, which backup are we referring to? auto or manual?

**Comment by neutrinog** [comment]
1. the default location should be `~/translationStudio/backups/`
2. it will be `~/translationStudio/backups/automatic/`

The backup setting is for where `~/translationStudio/backups/` is. So the automatic backup will just be in an `automatic` directory in there`.

**Comment by neutrinog** [comment]
@vleong2332 any progress on this?

**Comment by vleong2332** [comment]
A bit. I'm gonna work on it tonight.

**Pull request merged**
