### PR TITLE
Updated bootstrap.js to use the new version of the reporter

### LINKED ISSUE #57: update bootstrap to use latest version of reporter.
For the crash log we can just create a new temporary reporter instance in the global error catching hook rather than cluttering up the app scope

### PR DESCRIPTION
**Pull request by EmmittJ**
Fixed #57

### CODE REVIEW

**Comment by neutrinog** [comment]
the only change I would suggest is instantiating the reporter with the normal log file. that way other parts of the application can just use it. Then create a new instance of the reporter just for crash reports in the crash hook.

**Comment by EmmittJ** [comment]
I believe it already is?

**Comment by neutrinog** [comment]
see https://github.com/unfoldingWord-dev/ts-desktop/blob/da6b9d7ef8b264d22cef6a1b12ca67dc7d217b8b/app/js/bootstrap.js#L34

Also in order to create an instance of the reporter you now need to use
```
var myReporter = new reporter.instance(args)
```

with ES6 we're supposed to be able to be able to set it up so you can just du `new reporter(args)` but I couldn't get it working.

**Comment by EmmittJ** [comment]
Yeah, for some reason my local changes aren't being noticed by git. I can't add changes, so I am going to lcose this pull and revert to the upstream copy and hopefully that will work

**Pull request closed without merging**
